language: cpp

compiler:
  - gcc
before_script:
  - sudo apt-get install cmake 
  - mkdir build
  - cd build
  # build for x86_64
  - cmake -Dx86_64=ON .. 
  - make
  - cp ./source/main/testkit-stub ../dest/x86_64/
  - rm -rf *
  # build for i386
  - cmake -Di386=ON .. 
  - make
  - cp ./source/main/testkit-stub ../dest/i386/
  - rm -rf *
  # build for arm
  - cmake -D CMAKE_TOOLCHAIN_FILE=../arm_toolchain.cmake ..
  - make
  - cp ./source/main/testkit-stub ../dest/arm/
  - rm -rf *
  # build for android
  # install ndk
  # compile with ndk for all ABI
  # build apk
  # cp to ../dest/android/
script: ls -al ../dest/ 
